onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - keytar
  - tree-sitter-bash
  - tree-sitter-c
  - tree-sitter-c-sharp
  - tree-sitter-cli
  - tree-sitter-cpp
  - tree-sitter-css
  - tree-sitter-go
  - tree-sitter-haskell
  - tree-sitter-html
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-json
  - tree-sitter-php
  - tree-sitter-python
  - tree-sitter-query
  - tree-sitter-regex
  - tree-sitter-ruby
  - tree-sitter-rust
  - tree-sitter-scala
  - tree-sitter-typescript
